inventory/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.ProductsListView.as_view(),name="home-page"),
    path('productssearch/',views.ProductsSearch,name='products-search'),
    path('newproduct/',views.ProductsCreateView.as_view(),name='create-product'),
    path('product/<int:pk>/update/',views.ProductsUpdateView.as_view(),name='product-update'),
    path('product/<int:pk>/delete/',views.ProductDeleteView.as_view(),name='product-delete'),
    path('dashboard/',views.CategoryListView.as_view(),name='dashboard'),
    path('product/<int:pk>/',views.product_detail,name='product-detail'),
    path('newcategory/',views.CategoryCreateView.as_view(),name='newcategory'),
    path('newsupplier/', views.SupplierCreateView.as_view(), name='new-supplier'),
    path('suppliers/', views.SupplierListView.as_view(), name='supplier-list'),
    path('newdelivery/',views.DeliveryCreateView,name='new-delivery'),
    ]

sales/urls.py
from django.urls import path
from . import views


urlpatterns = [path('',views.sales,name="sales")]

users/urls.py
from django.urls import path
from . import views

urlpatterns =[path('',views.register,name='register')]

wangahtraders/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('inventory.urls')),
    path('register/',include('users.urls')),
    path('login/',auth_views.LoginView.as_view(template_name='users/login.html'),name='login'),
    path('logout/',auth_views.LogoutView.as_view(),name='logout'),
    path('sales/',include('sales.urls'))
    
 
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

inventory/models.py
from django.db import models
from PIL  import Image
# Create your models here.
from django.urls import reverse
from django.core.exceptions import ValidationError

class Category(models.Model):
    name = models.CharField(max_length=100, unique=True)
    parent = models.ForeignKey(
        'self',
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name='subcategories'
    )
    description = models.TextField(blank=True)

    class Meta:
        verbose_name_plural = 'Categories'

    def get_absolute_url(self):
        return reverse('dashboard')
    

    def __str__(self):
        # Show full path e.g., "Food & Beverages > Snacks"
        if self.parent:
            return f"{self.parent} > {self.name}"
        return self.name

class Supplier(models.Model):
    name = models.CharField(max_length=255)
    email = models.EmailField(blank=True, null=True)
    phone = models.CharField(max_length=20, blank=True, null=True)
    company_name = models.CharField(max_length=255, blank=True, null=True)
    product_categories = models.CharField(max_length=255, help_text="e.g., electronics, groceries")
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

        

class Products(models.Model):
    p_name = models.CharField(max_length=255,unique=True)
    p_description = models.TextField(max_length=200)
    p_price = models.DecimalField(max_digits=10,decimal_places=2)
    p_image = models.ImageField(default='default.jpg',upload_to='productsimg')
    p_costprice = models.DecimalField(max_digits=10,decimal_places=2,default=0)
   # supplier = models.ForeignKey(Supplier, on_delete=models.SET_NULL, null=True, related_name="products")
    p_stock = models.PositiveIntegerField(default=0)
    p_category = models.ForeignKey(
        Category,
        on_delete=models.CASCADE,
        null=True,
        related_name='products'
    )



    def clean(self):
        if self.p_costprice >= self.p_price:
            raise ValidationError("Buying price must be lower than selling price")

    
    def __str__(self):
        return(self.p_name)
    #access the created product
    def get_absolute_url(self):
        return reverse('product-detail',kwargs={'pk':self.pk})
    
    def  save(self):
        super().save()
        

        img = Image.open(self.p_image.path)

        if img.height > 300 or img.width > 300:
            output_size = (200,200)
            img.thumbnail(output_size)
            img.save(self.p_image.path)

sales/models.py
from django.db import models
from django.contrib.auth.models import User

users/models.py
from django.db import models

# Create your models here.

inventory/forms.py
# forms.py
from django import forms
from .models import Products

from .models import Category



class ProductsUpdateForm(forms.ModelForm):
    class Meta:
        model = Products
        fields = ['p_name','p_description','p_price','p_image']
        

users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms


class usercreateform(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ['username','email','password1','password2']

inventory/views.py
from django.shortcuts import render
from .models import Products,Category,Supplier
from django.views.generic import DetailView,CreateView,UpdateView,DeleteView,ListView
from .forms import ProductsUpdateForm
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.contrib import messages
from django.db.models import Q
from django.contrib.auth.mixins import LoginRequiredMixin
# Create your views here.




def ProductsSearch(request):
    if request.method == 'GET':
         searched = request.GET['q']
         #returned search results
         products = Products.objects.filter(Q(p_name__contains=searched)|Q(p_description__icontains=searched))
         return render(request,'inventory/search.html',{'searched':searched,'products':products})
  
    return render(request,'inventory/search.html',{})



class ProductsListView(LoginRequiredMixin,ListView):
    model = Products

    template_name = 'inventory/home.html'
    context_object_name = 'products'
    
    #To add extra context to a classbasedview
    '''
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Add custom context here
        context['extra_info'] = 'This is some extra info'
        return context
  '''

def product_detail(request, pk):
    product = get_object_or_404(Products, pk=pk)
    related_products = Products.objects.filter(p_category=product.p_category).exclude(pk=product.pk)

    return render(request, 'inventory/products_detail.html', {
        'product': product,
        'products': related_products
    })




class ProductsCreateView(CreateView):
    model = Products
    fields = ['p_name','p_description','p_image','p_price','p_costprice','p_category']

    #success_url = reverse_lazy('home-page')

    
    #adding messages
    def form_valid(self, form):
        response = super().form_valid(form)
        messages.success(self.request, "Product created successfully!")
        return response


class ProductsUpdateView(UpdateView):
    model = Products
    fields = ['p_name','p_description','p_image','p_price','p_costprice','p_category']

    #success_url = reverse_lazy('home-page')

    
    #adding messages
    def form_valid(self, form):
        response = super().form_valid(form)
        messages.success(self.request, "Product created successfully!")
        return response


class ProductDeleteView(DeleteView):
    model = Products

    success_url = reverse_lazy('home-page')


class CategoryListView(ListView):
    model = Category
   
    context_object_name = 'categories'

    def get_queryset(self):
        return Category.objects.prefetch_related('products').all()

class CategoryCreateView(CreateView):
    model = Category
    fields = '__all__'


class SupplierCreateView(CreateView):
    model = Supplier
    fields = '__all__'
    success_url = reverse_lazy('home-page')


class SupplierListView(ListView):
    model = Supplier
    context_object_name = 'suppliers'
    
def DeliveryCreateView(request):
    return render(request, 'inventory/delivery.html', {})


    #image format
    #saving images
    #saving categories

sales/views.py
from django.shortcuts import render
from django.http import request




# Create your views here.
def sales(request):
    return render(request,'sales/index.html')

users/views.py
from django.shortcuts import render,redirect
from .forms import usercreateform

def register(request):          
    if request.method == "POST":
        form = usercreateform(request.POST)
        if form.is_valid():
            form.save()
            return redirect('login')
    else:
        form = usercreateform()
    return render(request,'users/register.html',{'form':form})

inventory/templates/inventory/base.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'inventory/styles.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    
</head>
<body>
  <nav class="navbar navbar-expand-lg bg-body-tertiary fixed-top  ">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Wangah Traders</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          {% if user.is_superuser %}
          <li class="nav-item">
            <a class="nav-link  active" aria-current="page" href="{%url 'admin:index'%}">Admin</a>
          </li>
          {% endif %}
          <li class="nav-item">
            <a class="nav-link  active" aria-current="page" href="#">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link  active" aria-current="page" href="{%url 'home-page'%}">Products</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{%url 'dashboard'%}">Dashboard</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">sales</a>
          </li>
        
          <li class="nav-item dropdown">
             <a href="#" class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown" aria-expanded="false">Categories</a>
             <ul class="dropdown-menu">
        
            </ul>
          </li>
          {% if user.is_superuser %}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Actions
            </a>
            
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="{%url 'create-product'%}">Add Product</a></li>
              <li><a class="dropdown-item" href="{%url 'newcategory'%}">New category</a></li>
              <li><a class="dropdown-item" href="{%url 'new-supplier'%}">New supplier</a></li>
              <li><a class="dropdown-item" href="{%url 'new-delivery'%}">New Order </a></li>

            </ul>
           
          </li>
           {% endif %}

         
        </ul>
        <form class="d-flex" role="search" action="{%url 'products-search' %}" id="search">
          {%csrf_token%}
          <input class="form-control me-2"  name="q" value="{{ request.GET.q }}" type="search" placeholder="Search" aria-label="Search"/>
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>

          {% if user.is_authenticated %}
        <form action="{% url 'logout' %}" method="post">
         {%csrf_token%}
       <li class="btn mt-2 nav-item ms-2" >
         <button class="btn btn-outline-danger" type="submit">logout</button>
    
       </li>
       </form>
       {% else %}

    <div class=" ms-2 d-flex justify-content-center" >
      <li class="nav-item me-2 mt-2  nav-link ">
        <a class="btn active" aria-current="page" href="{%url 'login'%}">Login</a>
      </li>
      <li class="nav-item me-2 mt-2  nav-link">
        <a class="btn active" aria-current="page" href="{%url 'register'%}">Register</a>
      </li>
   
    </div>
       {% endif %}
        
      </div>
    </div>


  </nav>



 <div id="messages">
   
  {% if messages %}
    {% for message in messages %}
      <div id="alert alert-{{ message.tags }}">
        {{ message }}
      </div>
    {% endfor %}
  {% endif %}
  
 </div>

   
      
     <main class="container" id="main-content">
          {% block content %}

          {% endblock %}
          <!-- Footer -->


      </main>


      <footer class="bg-dark text-white text-center text-lg-start mt-5">
        <div class="container p-4">
          <div class="row">
            
            <!-- About Section -->
            <div class="col-lg-4 col-md-6 mb-4 mb-md-0">
              <h5 class="text-uppercase">MyShop</h5>
              <p>
                Your trusted place for quality products and amazing deals. We value every customer.
              </p>
            </div>
      
            <!-- Links -->
            <div class="col-lg-4 col-md-6 mb-4 mb-md-0">
              <h5 class="text-uppercase">Links</h5>
              <ul class="list-unstyled mb-0">
                <li><a href="#" class="text-white text-decoration-none">Home</a></li>
                <li><a href="#" class="text-white text-decoration-none">Products</a></li>
                <li><a href="#" class="text-white text-decoration-none">Sales</a></li>
                <li><a href="#" class="text-white text-decoration-none">Contact</a></li>
              </ul>
            </div>
      
            <!-- Contact -->
            <div class="col-lg-4 col-md-12 mb-4 mb-md-0">
              <h5 class="text-uppercase">Contact</h5>
              <p>Email: wangahtraders@gmail.com</p>
              <p>Phone: +254 719 689361</p>
              <p>Location: Githunguri, near County Pride hotel</p>
            </div>
          </div>
        </div>
      
        <!-- Copyright -->
        <div class="text-center p-3 bg-secondary">
          © 2025 MyShop. All rights reserved.
        </div>
      </footer>
      

<script src="{% static 'inventory/main.js' %}"></script>
<!-- Bootstrap 5.3 JS -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>

</body>
</html>

</body>
</html>

inventory/templates/inventory/category_form.html
{%extends 'inventory/base.html'%}
{%load crispy_forms_tags%}
{%block content%}
  <div id="reg">

    <div class="container d-flex justify-content-center align-items-center" style="height: 100vh;">
      <form method="post" class="card p-4 shadow" style="min-width: 300px;">
          {% csrf_token %}
          <h2 class="text-center mb-3">New Category</h2>
          {{ form.as_p }}
          <button type="submit" class="btn btn-primary w-100">Done</button>
          <a class="btn btn-primary w-100" type="button" href="{% url 'dashboard' %}">Cancel</a>
        
      </form>
  </div>
  </div>
  
{%endblock%}

inventory/templates/inventory/category_list.html
{%extends 'inventory/base.html'%}
   
    {%block content%}

    <div id="categories" >
      {% for category in categories %}
     
    
       {% if not category.parent %}
        <h1 class="text-center" id="category-name">{{category.name}}</h1>
        {%for subcategory in category.subcategories.all%}
        <div id="subcategory">
        <h1 id="category-name">{{subcategory.name}}</h1>
        <div id="main">
          {%if subcategory.products_set %}
          <h1>md</h1>
          {%else%}
   

          {{subcategory.products_set}}
          {% endif %}

        {%for product in subcategory.products.all %}
             
        <div id="items-container">
          
          <a  href="{% url 'product-detail' product.pk %}">

<div id="image-part">

<img src="{{ product.p_image.url }}" alt="Product here" width="185" height="185" >
</a>
</div>
<div id="name">

<p>{{product.p_name}}</p>


</div>


<div id="price" style="font-size: medium;">
<p>KSh {{product.p_price}} </p>

</div>

<div id="price">
<p>{{product.p_stock}} items left</p>
</div>

<div id="cart">
<button class="btn btn-warning">Add to cart</button>

</div>  


  
         
          </div>
       
       </a>
        {%endfor%}
      </div>
    </div>
   
        {%endfor%}
     
       {% endif%}
     
      {% endfor %}
    </div>







    {%endblock%}

inventory/templates/inventory/delivery.html
{% extends 'inventory/base.html'%}
{% load crispy_forms_tags %}
{% block content%}
<h1>order recieved page</h1>
{% endblock %}

inventory/templates/inventory/home.html
{%extends 'inventory/base.html'%}
   
    {%block content%}

 
   
 
 <div id="main">

    {%for product in products%}
   

            
          
        <div class="container" id="items-container">
          
                            <a  href="{% url 'product-detail' product.pk %}">

            <div id="image-part">

                <img src="{{ product.p_image.url }}" alt="Product here" width="185" height="185" >
                </a>
            </div>
            <div id="name">
            
                <p>{{product.p_name}}</p>
            
             
            </div>
    
         
            <div id="price" style="font-size: medium;">
                <p>KSh {{product.p_price}} </p>
             
            </div>
    
            <div id="price">
                  <p>{{product.p_stock}} items left</p>
            </div>
            
            <div id="cart">
                  <button class="btn btn-warning">Add to cart</button>
           
               </div>  
    

       
        </div>
 
 

     
    

  
   
        
        
       
     
  


        {%endfor %}
    
</div> 


       
 
    {%endblock%}

inventory/templates/inventory/products_confirm_delete.html
{%extends 'inventory/base.html'%}
{%load crispy_forms_tags%}
{%block content%}
  <div id="delete">
    <form  method="POST" enctype="multipart/form-data">
      
            {% csrf_token %}
            <h1 >Are you sure you want to delete "{{object.p_name}}"</h1>
          
          <div id="deletebtns">
            <button  class="btn btn-outline-danger" type="submit">Delete</button>
            <a class="btn btn-outline-success " href="{%url 'product-detail' object.id%}">cancel</a>

          </div>
     
       </form>
  </div>

{%endblock%}

inventory/templates/inventory/products_detail.html
{%extends 'inventory/base.html'%}
{%load crispy_forms_tags%}
{%block content%}

        <div class="container" id="detail-container" style="box-shadow: rgba(0, 0, 0, 0.1) 0px 4px 12px;">
 
           <div id="image-part">
               <img src="{{ product.p_image.url }}" alt="Product here" width="370" height="370">
 
           </div>

          <div class="container" id="grouping">
            <div id="product-name">
           
                <p>{{product.p_name}}</p>
                <p>Ksh {{product.p_price}}</p>
             
            </div>
  
         
            <div id="description">
                <p>{{product.p_description}}</p>
             
            </div>
       {%if user.is_superuser%} 
                <a  class="btn btn-outline-danger" href="{%url 'product-delete' product.pk %}" type="button">Delete</a></button>
               <a class="btn btn-outline-success" href="{% url 'product-update' product.pk %}" type="button">Edit</a>
  {%endif%}
          </div>
        
        </div>  

 
       
     <div id="main" class="container" style="box-shadow: rgba(0, 0, 0, 0.1) 0px 4px 12px;">
       <h1 class="container" style="border-bottom: 1px black solid;">Related Products</h1>
        {%for product in products%}
       
    
          <a href="{% url 'product-detail' product.pk %}">
         
              
            <div id="items-container">
              
                
                <div id="image-part">
                    <img src="{{ product.p_image.url }}" alt="Product here" width="185" height="185" >
        
                </div>
                <div id="description">
                
                    <p>{{product.p_description}}</p>
                
                 
                </div>
        
             
                <div id="price">
                    <p>KSh {{product.p_price}} </p>
                 
                </div>
        
                <div id="edit-btn">
    
                </div>
                
    
        
    
           
            </div>
         
            </a>
     
    
        
        
    
      
       
            
            
           
         
      
    
    
            {%endfor %}
        
    </div> 
    
    
     
{%endblock%}

inventory/templates/inventory/products_form.html
{%extends 'inventory/base.html'%}
{%load crispy_forms_tags%}
{%block content%}
  <div id="reg">

    <div class="container d-flex justify-content-center align-items-center" style="height: 100vh; ">
      <form method="post" class="card p-4 shadow" style="min-width: 300px;" enctype="multipart/form-data" >
          {% csrf_token %}
          <h2 class="text-center mb-3">New-item</h2>
          {{ form | crispy }}
          <button type="submit" class="btn btn-primary w-100">Done</button>
          <a class="btn btn-danger w-100" type="button" href="{% url 'dashboard' %}">Cancel</a>
        
      </form>
  </div>
  </div>

{%endblock%}

inventory/templates/inventory/search.html
{%extends 'inventory/base.html'%}
{%block content%}
{%if searched%}

<h1>

   
    {%if products%} 
  

 
   
  
<div id="main"  >
      {%for product in products%}

            
          
<div class="container" id="items-container">
          
        <a  href="{% url 'product-detail' product.pk %}">

<div id="image-part">

<img src="{{ product.p_image.url }}" alt="Product here" width="185" height="185" >
</a>
</div>
<div id="name">

<p>{{product.p_name}}</p>


</div>


<div id="price" style="font-size: medium;">
<p>KSh {{product.p_price}} </p>

</div>

<div id="price">
<p>{{product.p_stock}} items left</p>
</div>

<div id="cart">
<button class="btn btn-warning">Add to cart</button>

</div>  



</div>

  {%endfor %}
    
</div>


  
    {%else%}
    <h2>Item not found </h2>

    {%endif%}

 

</div>

   
</div>

{%endif%}

     
{%endblock%}

inventory/templates/inventory/supplier_form.html
{%extends 'inventory/base.html'%}
{%load crispy_forms_tags%}
{%block content%}
  <div id="reg">

    <div class="container d-flex justify-content-center align-items-center" style="height: 100vh;">
      <form method="post" class="card p-4 shadow" style="min-width: 300px;">
          {% csrf_token %}
          <h2 class="text-center mb-3">New Supplier</h2>
          {{ form.as_p }}
          <button type="submit" class="btn btn-primary w-100">Done</button>
          <a class="btn btn-primary w-100" type="button" href="{% url 'dashboard' %}">Cancel</a>
        
      </form>
  </div>
  </div>
  
{%endblock%}

inventory/templates/inventory/supplier_list.html
{%extends 'inventory/base.html'%}
{%load crispy_forms_tags%}
{%block content%}



<table class="table table-bordered container" >
  
    <thead class="thead-dark">
      <tr >
        <th scope="col">#</th>
        <th scope="col">Name</th>
        <th scope="col">Email</th>
        <th scope="col">company_name</th>
        <th scope="col">phone</th>
        <th scope="col">products</th>
      </tr>
    </thead>
      {%for supplier in suppliers%}
    <tbody>
   
      <tr>
        <th scope="row">{{supplier.id}}</th>
        <td>{{supplier.name}}</td>
        <td>{{supplier.email}}</td>
        <td>{{supplier.company_name}}</td>
        <td>{{supplier.phone}}</td>
        <td>{{supplier.product_categories}}</td>
     
      </tr>
  
    
    </tbody>
    {%endfor%}
  </table>
  
{%endblock%}

sales/templates/sales/index.html
{% extends 'inventory/base.html' %}

{%block content%}


<div class="container mt-4">
    <div class="table-responsive">
      <table class="table table-bordered invoice-table align-middle">
        <thead class="table-light text-center">
          <tr>
            <th>Item</th>
            <th>Description</th>
            <th>Unit Price</th>
            <th>Quantity</th>
            <th>Discount</th>
            <th>Tax 1</th>
            <th>Subtotal</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <!-- Item Row -->
          <tr>
            <td>
              <select>
                <option>Item</option>
                <option>Item A</option>
                <option>Item B</option>
              </select>
            </td>
            <td><input type="text" placeholder="Description"></td>
            <td><input type="number" placeholder="Unit Price"></td>
            <td><input type="number" placeholder="Quantity"></td>
            <td class="d-flex">
              <input type="number" placeholder="Disc." class="me-1"><span class="mt-2">%</span>
            </td>
            <td>
              <select>
                <option>Tax 1</option>
                <option>0%</option>
                <option>16%</option>
              </select>
            </td>
            <td>Ksh 0.00</td>
            <td class="text-center">
              <span class="remove-btn">&minus;</span>
            </td>
          </tr>
          <!-- Repeat for more rows -->
          <tr>
            <td>
              <select>
                <option>Item</option>
                <option>Item A</option>
                <option>Item B</option>
              </select>
            </td>
            <td><input type="text" placeholder="Description"></td>
            <td><input type="number" placeholder="Unit Price"></td>
            <td><input type="number" placeholder="Quantity"></td>
            <td class="d-flex">
              <input type="number" placeholder="Disc." class="me-1"><span class="mt-2">%</span>
            </td>
            <td>
              <select>
                <option>Tax 1</option>
                <option>0%</option>
                <option>16%</option>
              </select>
            </td>
            <td>Ksh 0.00</td>
            <td class="text-center">
              <span class="remove-btn">&minus;</span>
            </td>
          </tr>
        </tbody>
      </table>
      <!-- Add Button -->
      <button class="btn btn-outline-primary">
        <span class="me-1">+</span> Add
      </button>
    </div>
  
    <!-- Totals Box -->
    <div class="mt-3 float-end text-end">
      <div><strong>Items Total:</strong> Ksh 0.00</div>
      <div><strong>Total:</strong> Ksh 0.00</div>
    </div>
  </div>
{%endblock%}

users/templates/users/login.html
{% extends 'inventory/base.html' %}
{% block content %}
   
      <div class="container d-flex justify-content-center align-items-center" style="height: 100vh;">
         <form method="post" class="card p-4 shadow" style="min-width: 300px;">
             {% csrf_token %}
             <h2 class="text-center mb-3">Login</h2>
             {{ form.as_p }}
             <button type="submit" class="btn btn-primary w-100">Login</button>
            <div class="container d-flex"> 
                <p class="text-justify" style="font-size:small;">Don't have an account</p>
                <a style="font-size:small;" href="{%url 'register'%}">Sign up</a></div>
         </form>
     </div>

{% endblock %} 

users/templates/users/register.html
{% extends 'inventory/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
  
<div class="container d-flex justify-content-center align-items-center" style="height: 100vh;">
   <form method="post" class="card p-4 shadow" style="min-width: 300px;">
       {% csrf_token %}
       <h2 class="text-center mb-3">Register</h2>
       {{ form | crispy }}
       <button type="submit" class="btn btn-primary w-100">Register</button>
       <div class="container d-flex"> 
        <p class="text-justify" style="font-size:small;">Already have an account</p>
        <a style="font-size:small;" href="{%url 'login'%}">Sign In</a></div>
   </form>
</div>

{% endblock %}